[theme]

# Mengubah warna latar belakang utama menjadi abu-abu muda
backgroundColor = "#161A30"

# Mengubah warna sidebar menjadi oranye
secondaryBackgroundColor = "#333446"

# Mengubah warna teks agar tetap terbaca
textColor = "#EFEEEA"
