[theme]

# Tentukan tema dasar agar tidak kembali ke hitam
base = "dark"

# Mengubah warna latar belakang utama menjadi abu-abu muda
backgroundColor = "#E8988A"

# Mengubah warna sidebar menjadi oranye
secondaryBackgroundColor = "#D4C9BE"

# Mengubah warna teks agar tetap terbaca
textColor = "#254D70"
