[theme]

# Mengubah warna latar belakang utama menjadi abu-abu muda
backgroundColor = "#27548A"

# Mengubah warna sidebar menjadi oranye
secondaryBackgroundColor = "#D4C9BE"

# Mengubah warna teks agar tetap terbaca
textColor = "#254D70"
